[build]
  base = "client"
  command = "npm run build"
  publish = "build"

  [build.environment]
    NODE_VERSION = "18"
    REACT_APP_API_URL = "https://roomnmeal.onrender.com"

# API redirects only
[[redirects]]
  from = "/api/*"
  to = "https://roomnmeal.onrender.com/api/:splat"
  status = 200
  force = true
