[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

# Redirects for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects to backend
[[redirects]]
  from = "/api/*"
  to = "https://roomnmeal.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/socket.io/*"
  to = "https://roomnmeal.onrender.com/socket.io/:splat"
  status = 200
  force = true

# Headers for proper MIME types
[[headers]]
  for = "/static/css/*"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"